# Generated by Django 3.2.3 on 2021-07-13 12:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_auto_20210713_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Multi_Locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), size=None), null=True, size=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='multi_uploads',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, upload_to='covers/'), null=True, size=None),
        ),
    ]
