# Generated by Django 3.2.3 on 2021-07-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_auto_20210713_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Google_maps_link',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Plus_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Radius',
        ),
        migrations.RemoveField(
            model_name='location',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='location',
            name='Latitude1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='Longitude1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
