# Generated by Django 3.2.3 on 2021-07-25 16:09

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0041_alter_location_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Multi_Locations',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), size=2), null=True, size=255),
        ),
    ]
