# Generated by Django 3.2.3 on 2021-07-25 16:40

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0042_alter_asset_multi_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='Multi_Locations',
        ),
        migrations.AddField(
            model_name='asset',
            name='latitude1',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), null=True, size=2),
        ),
        migrations.AddField(
            model_name='asset',
            name='longitude1',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), null=True, size=2),
        ),
    ]
