# Generated by Django 3.2.3 on 2021-07-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0046_alter_asset_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='count',
        ),
    ]
