# Generated by Django 3.2.3 on 2021-07-29 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0047_remove_asset_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='covers/')),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='Locations',
            field=models.ManyToManyField(to='event.Location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='files',
            field=models.ManyToManyField(to='event.File'),
        ),
    ]
