# Generated by Django 3.2.3 on 2021-07-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0048_auto_20210729_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileUplaod',
        ),
    ]
